# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd02b8f4f2bca41ef29766a6af9b3533f135b29f5d2a5d879d61ad95811666cdfb8747a88906647ad5a88b991dcb21c7939fe4e6bddee7bb0f097466d576ae6

test:
  secret_key_base: 4fc0a2ce2db6f7229eae4dfd1e85d15bae378e779f2471ac250a4b1b54c504a2ec8403732ae26ddf81aab5c00cb5f2304f7130159347570b8c2c1809a1bfc89b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
